=== charrls/Documentos-XML/src/arboles.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT arboles (especie)*>
        <!ELEMENT especie (nombre, informacion)>
        <!ELEMENT informacion (nombre_comun?, vegetaci칩n?, altura?, forma_estructura?,color_primavera?,color_oto침o?,resistencia_heladas?)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT nombre_comun (#PCDATA)>
        <!ELEMENT vegetaci칩n (#PCDATA)>
        <!ELEMENT altura (#PCDATA)>
        <!ELEMENT forma_estructura (#PCDATA)>
        <!ELEMENT color_primavera (#PCDATA)>
        <!ELEMENT color_oto침o (#PCDATA)>
        <!ELEMENT resistencia_heladas (#PCDATA)>

=== charrls/Documentos-XML/src/arboles.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE arboles SYSTEM "arboles.dtd">

<arboles>

    <especie>
        <nombre>Acer monspessulanum</nombre>
        <informacion>
            <nombre_comun>Arce de Montpellier, Arce menor</nombre_comun>
            <vegetación>Caducifolio</vegetación>
            <altura>De 6 a 10 metros</altura>
            <forma_estructura>Copa esférica. Tronco principal recto con bifurcaciones. Ramaje colgante</forma_estructura>
            <color_primavera>Haz verde brillante, envés verde blanquecino</color_primavera>
            <resistencia_heladas>Heladas fuertes (hasta -15ºC)</resistencia_heladas>
        </informacion>
    </especie>

    <especie>
        <nombre>Olea europea</nombre>
        <informacion>
            <nombre_comun>Olivo</nombre_comun>
            <vegetación>Perenne</vegetación>
            <altura>De 8 a 15 metros</altura>
            <forma_estructura>Copa irregular. Tronco principal irregular con bifurcaciones.</forma_estructura>
        </informacion>
    </especie>

    <especie>
        <nombre>Ramaje tortuoso</nombre>
        <informacion>
            <color_primavera>Haz verde oscuro, envés verde plateado</color_primavera>
            <resistencia_heladas>Heladas medias (hasta -10ºC)</resistencia_heladas>
        </informacion>
    </especie>

    <especie>
        <nombre>Platanus orientalis</nombre>
        <informacion>
            <nombre_comun>Platano</nombre_comun>
            <vegetación>Caducifolio</vegetación>
            <altura>De 20 a 25 metros</altura>
            <forma_estructura>Copa ovoidal. Tronco principal recto. Ramaje expandido</forma_estructura>
            <color_primavera>Haz verde medio, enves verde claro</color_primavera>
            <color_otoño>Ocre</color_otoño>
            <resistencia_heladas>Heladas fuertes (hasta -20ºC)</resistencia_heladas>
        </informacion>
    </especie>

    <especie>
        <nombre>Quercus ilex</nombre>
        <informacion>
            <nombre_comun>Encina</nombre_comun>
            <vegetación>Perenne</vegetación>
            <altura>En torno a 25 metros</altura>
            <forma_estructura>Copa esférica o elíptica irregular. Tronco principal recto. Ramaje tortuoso</forma_estructura>
            <color_primavera>Plateado en hojas jóvenes. En hojas antiguas, haz verde oscuro, envés plateado</color_primavera>
            <resistencia_heladas>Heladas fuertes (hasta -15ºC)</resistencia_heladas>
        </informacion>
    </especie>

</arboles>
