=== charrls/Documentos-XML/src/factura.dtd
<?xml version="1.0" encoding="UTF-8"?>

        <!ELEMENT facturas (factura)*>
        <!ELEMENT factura (business_contact, general_data, description_services)>

        <!ELEMENT business_contact (business_name,street_address, city, state, zip_code, email, website)>

        <!ELEMENT general_data (bill_to, ship_to, invoice_details)>
        <!ELEMENT bill_to (client_name, street_address, city, state, zip_code)>
        <!ELEMENT ship_to (client_name, street_address, city, state, zip_code)>
        <!ELEMENT invoice_details (invoice_n, invoice_date, terms)>

        <!ELEMENT description_services (goods_services)*>
        <!ELEMENT goods_services (product, description, qty, rate, amount)>


        <!ELEMENT business_name (#PCDATA)>
        <!ELEMENT street_address (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT state (#PCDATA)>
        <!ELEMENT zip_code (#PCDATA)>
        <!ELEMENT email (#PCDATA)>
        <!ELEMENT website (#PCDATA)>
        <!ELEMENT client_name (#PCDATA)>
        <!ELEMENT invoice_n (#PCDATA)>
        <!ELEMENT invoice_date (#PCDATA)>
        <!ELEMENT terms (#PCDATA)>
        <!ELEMENT product (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT qty (#PCDATA)>
        <!ELEMENT rate (#PCDATA)>
        <!ELEMENT amount (#PCDATA)>

=== charrls/Documentos-XML/src/factura.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE facturas SYSTEM "factura.dtd">

<facturas>

    <factura>

        <business_contact>
            <business_name></business_name>
            <street_address></street_address>
            <city></city>
            <state></state>
            <zip_code></zip_code>
            <email></email>
            <website></website>
        </business_contact>

        <general_data>
            <bill_to>
                <client_name></client_name>
                <street_address></street_address>
                <city></city>
                <state></state>
                <zip_code></zip_code>
            </bill_to>
            <ship_to>
                <client_name></client_name>
                <street_address></street_address>
                <city></city>
                <state></state>
                <zip_code></zip_code>
            </ship_to>
            <invoice_details>
                <invoice_n></invoice_n>
                <invoice_date></invoice_date>
                <terms></terms>
            </invoice_details>
        </general_data>

        <description_services>
            <goods_services>
                <product></product>
                <description></description>
                <qty></qty>
                <rate></rate>
                <amount></amount>
            </goods_services>
        </description_services>

    </factura>

</facturas>
